# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipinfo < Formula
  desc "A simple command to get your ip info"
  homepage "https://github.com/0x4richard/ipinfo"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/0x4richard/ipinfo/releases/download/v0.1.0/ipinfo_0.1.0_Darwin_arm64.tar.gz"
      sha256 "23ff8915e0ac359d6ceed5bfddca1f299ccd837f84f8b3487c613a136cab6275"

      def install
        bin.install "ipinfo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/0x4richard/ipinfo/releases/download/v0.1.0/ipinfo_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "f4b91e43e8e9938d93368dc02ad2adc00e2f379a94744d7d72c49c7b6f0ce689"

      def install
        bin.install "ipinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/0x4richard/ipinfo/releases/download/v0.1.0/ipinfo_0.1.0_Linux_x86_64.tar.gz"
      sha256 "13957d7e6c176148e10a9169f2a30238ebc017fd30576396deacc6902ac92c94"

      def install
        bin.install "ipinfo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/0x4richard/ipinfo/releases/download/v0.1.0/ipinfo_0.1.0_Linux_armv6.tar.gz"
      sha256 "f7b7e664ef1d334455cd2bd470f15230cedca89c0058e3d5460639857dbbc8e5"

      def install
        bin.install "ipinfo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0x4richard/ipinfo/releases/download/v0.1.0/ipinfo_0.1.0_Linux_arm64.tar.gz"
      sha256 "cb2e837292b59daebe6982c94a75fb9fed7306189c4a8d4651a2daa5bac07bd7"

      def install
        bin.install "ipinfo"
      end
    end
  end
end
